### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by ImNotSoftik** [AlexProgrammerDE/SoulFire#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your issue

[19:22:58 ERROR] [ClientCommandManager]: Error while starting bot attack!
io.grpc.StatusRuntimeException: UNKNOWN: Application error processing RPC
        at io.grpc.Status.asRuntimeException(Status.java:533) ~[?:?]
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481) ~[?:?]
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574) ~[?:?]
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72) ~[?:?]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742) ~[?:?]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[?:?]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[?:?]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[19:22:58 ERROR] [SoulFire]: февр. 14, 2024 7:22:58 PM io.grpc.internal.SerializingExecutor run
[19:22:58 ERROR] [SoulFire]: SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@9545d6b
[19:22:58 ERROR] [SoulFire]: java.lang.IllegalStateException: failed to create a child event loop
[19:22:58 ERROR] [SoulFire]:    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
[19:22:58 ERROR] [SoulFire]:    at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:68)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:104)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:97)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:90)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:79)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:62)
[19:22:58 ERROR] [SoulFire]:    at net.pistonmaster.soulfire.server.protocol.netty.SWNettyHelper.createEventLoopGroup(SWNettyHelper.java:77)
[19:22:58 ERROR] [SoulFire]:    at net.pistonmaster.soulfire.server.AttackManager.start(AttackManager.java:154)
[19:22:58 ERROR] [SoulFire]:    at net.pistonmaster.soulfire.server.SoulFireServer.startAttack(SoulFireServer.java:291)
[19:22:58 ERROR] [SoulFire]:    at net.pistonmaster.soulfire.server.grpc.AttackServiceImpl.startAttack(AttackServiceImpl.java:36)
[19:22:58 ERROR] [SoulFire]:    at net.pistonmaster.soulfire.grpc.generated.AttackServiceGrpc$MethodHandlers.invoke(AttackServiceGrpc.java:334)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
[19:22:58 ERROR] [SoulFire]:    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:22:58 ERROR] [SoulFire]:    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:22:58 ERROR] [SoulFire]:    at java.base/java.lang.Thread.run(Thread.java:1583)
[19:22:58 ERROR] [SoulFire]: Caused by: java.lang.RuntimeException: failed to allocate memory for io_uring ring; try raising memlock limit (see getrlimit(RLIMIT_MEMLOCK, ...) or ulimit -l): Невозможно выделить память
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.Native.ioUringSetup(Native Method)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.Native.createRingBuffer(Native.java:201)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoop.<init>(IOUringEventLoop.java:73)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.newChild(IOUringEventLoopGroup.java:121)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.newChild(IOUringEventLoopGroup.java:31)
[19:22:58 ERROR] [SoulFire]:    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
[19:22:58 ERROR] [SoulFire]:    ... 23 more

### How can we reproduce what you got?

[19:22:58 ERROR] [ClientCommandManager]: Error while starting bot attack!
io.grpc.StatusRuntimeException: UNKNOWN: Application error processing RPC
        at io.grpc.Status.asRuntimeException(Status.java:533) ~[?:?]
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481) ~[?:?]
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574) ~[?:?]
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72) ~[?:?]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742) ~[?:?]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[?:?]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[?:?]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[19:22:58 ERROR] [SoulFire]: февр. 14, 2024 7:22:58 PM io.grpc.internal.SerializingExecutor run
[19:22:58 ERROR] [SoulFire]: SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@9545d6b
[19:22:58 ERROR] [SoulFire]: java.lang.IllegalStateException: failed to create a child event loop
[19:22:58 ERROR] [SoulFire]:    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
[19:22:58 ERROR] [SoulFire]:    at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:68)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:104)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:97)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:90)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:79)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:62)
[19:22:58 ERROR] [SoulFire]:    at net.pistonmaster.soulfire.server.protocol.netty.SWNettyHelper.createEventLoopGroup(SWNettyHelper.java:77)
[19:22:58 ERROR] [SoulFire]:    at net.pistonmaster.soulfire.server.AttackManager.start(AttackManager.java:154)
[19:22:58 ERROR] [SoulFire]:    at net.pistonmaster.soulfire.server.SoulFireServer.startAttack(SoulFireServer.java:291)
[19:22:58 ERROR] [SoulFire]:    at net.pistonmaster.soulfire.server.grpc.AttackServiceImpl.startAttack(AttackServiceImpl.java:36)
[19:22:58 ERROR] [SoulFire]:    at net.pistonmaster.soulfire.grpc.generated.AttackServiceGrpc$MethodHandlers.invoke(AttackServiceGrpc.java:334)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
[19:22:58 ERROR] [SoulFire]:    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
[19:22:58 ERROR] [SoulFire]:    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:22:58 ERROR] [SoulFire]:    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:22:58 ERROR] [SoulFire]:    at java.base/java.lang.Thread.run(Thread.java:1583)
[19:22:58 ERROR] [SoulFire]: Caused by: java.lang.RuntimeException: failed to allocate memory for io_uring ring; try raising memlock limit (see getrlimit(RLIMIT_MEMLOCK, ...) or ulimit -l): Невозможно выделить память
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.Native.ioUringSetup(Native Method)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.Native.createRingBuffer(Native.java:201)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoop.<init>(IOUringEventLoop.java:73)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.newChild(IOUringEventLoopGroup.java:121)
[19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.newChild(IOUringEventLoopGroup.java:31)
[19:22:58 ERROR] [SoulFire]:    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
[19:22:58 ERROR] [SoulFire]:    ... 23 more

### SoulFire/Error Logs

[19:22:58 ERROR] [ClientCommandManager]: Error while starting bot attack! io.grpc.StatusRuntimeException: UNKNOWN: Application error processing RPC         at io.grpc.Status.asRuntimeException(Status.java:533) ~[?:?]         at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481) ~[?:?]         at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574) ~[?:?]         at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72) ~[?:?]         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742) ~[?:?]         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[?:?]         at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[?:?]         at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[?:?]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]         at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] [19:22:58 ERROR] [SoulFire]: февр. 14, 2024 7:22:58 PM io.grpc.internal.SerializingExecutor run [19:22:58 ERROR] [SoulFire]: SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@9545d6b [19:22:58 ERROR] [SoulFire]: java.lang.IllegalStateException: failed to create a child event loop [19:22:58 ERROR] [SoulFire]:    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88) [19:22:58 ERROR] [SoulFire]:    at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:68) [19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:104) [19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:97) [19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:90) [19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:79) [19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.<init>(IOUringEventLoopGroup.java:62) [19:22:58 ERROR] [SoulFire]:    at net.pistonmaster.soulfire.server.protocol.netty.SWNettyHelper.createEventLoopGroup(SWNettyHelper.java:77) [19:22:58 ERROR] [SoulFire]:    at net.pistonmaster.soulfire.server.AttackManager.start(AttackManager.java:154) [19:22:58 ERROR] [SoulFire]:    at net.pistonmaster.soulfire.server.SoulFireServer.startAttack(SoulFireServer.java:291) [19:22:58 ERROR] [SoulFire]:    at net.pistonmaster.soulfire.server.grpc.AttackServiceImpl.startAttack(AttackServiceImpl.java:36) [19:22:58 ERROR] [SoulFire]:    at net.pistonmaster.soulfire.grpc.generated.AttackServiceGrpc$MethodHandlers.invoke(AttackServiceGrpc.java:334) [19:22:58 ERROR] [SoulFire]:    at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) [19:22:58 ERROR] [SoulFire]:    at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) [19:22:58 ERROR] [SoulFire]:    at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) [19:22:58 ERROR] [SoulFire]:    at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) [19:22:58 ERROR] [SoulFire]:    at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) [19:22:58 ERROR] [SoulFire]:    at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351) [19:22:58 ERROR] [SoulFire]:    at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861) [19:22:58 ERROR] [SoulFire]:    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [19:22:58 ERROR] [SoulFire]:    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) [19:22:58 ERROR] [SoulFire]:    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [19:22:58 ERROR] [SoulFire]:    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [19:22:58 ERROR] [SoulFire]:    at java.base/java.lang.Thread.run(Thread.java:1583) [19:22:58 ERROR] [SoulFire]: Caused by: java.lang.RuntimeException: failed to allocate memory for io_uring ring; try raising memlock limit (see getrlimit(RLIMIT_MEMLOCK, ...) or ulimit -l): Невозможно выделить память [19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.Native.ioUringSetup(Native Method) [19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.Native.createRingBuffer(Native.java:201) [19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoop.<init>(IOUringEventLoop.java:73) [19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.newChild(IOUringEventLoopGroup.java:121) [19:22:58 ERROR] [SoulFire]:    at io.netty.incubator.channel.uring.IOUringEventLoopGroup.newChild(IOUringEventLoopGroup.java:31) [19:22:58 ERROR] [SoulFire]:    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) [19:22:58 ERROR] [SoulFire]:    ... 23 more

### SoulFire Version

latest

### Java Version

 openjdk version "21-ea" 2023-09-19 OpenJDK Runtime Environment (build 21-ea+30-2426) OpenJDK 64-Bit Server VM (build 21-ea+30-2426, mixed mode, sharing)

**Comment by AlexProgrammerDE** [comment]
```
 [19:22:58 ERROR] [SoulFire]: Caused by: java.lang.RuntimeException: failed to allocate memory for io_uring ring; try raising memlock limit (see getrlimit(RLIMIT_MEMLOCK, ...) or ulimit -l): Невозможно выделить память
```
try raising memlock limit (see getrlimit(RLIMIT_MEMLOCK, ...) or ulimit -l):

**Comment by ImNotSoftik** [comment]
> ```
>  [19:22:58 ERROR] [SoulFire]: Caused by: java.lang.RuntimeException: failed to allocate memory for io_uring ring; try raising memlock limit (see getrlimit(RLIMIT_MEMLOCK, ...) or ulimit -l): Невозможно выделить память
> ```
> 
> try raising memlock limit (see getrlimit(RLIMIT_MEMLOCK, ...) or ulimit -l):

https://github.com/AlexProgrammerDE/SoulFire/issues/330#issuecomment-1943925532
