### ISSUE TITLE
Joining on Java 1.20.1 servers isn't possible

### ISSUE THREAD

**Issue by TheDevMinerTV** [AlexProgrammerDE/SoulFire#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your issue

Joining onto a [hyperion](https://github.com/andrewgazelka/hyperion) server (1.20.1 only) doesn't work with SoulFire 1.7.0.
```
[00:53:35 INFO] [Bot_1]: Joined server at position: X -656 Y 18 Z -1695
[00:53:37 ERROR] [SoulFireConsole]: net.lenni0451.lambdaevents.utils.EventException: Exception occurred in 'ClientboundRegistryDataPacket' handler in 'com.soulfiremc.server.protocol.bot.SessionDataManager'
[00:53:37 ERROR] [SoulFireConsole]: Caused by: java.lang.ClassCastException: class com.github.steveice10.opennbt.tag.builtin.LongTag cannot be cast to class com.github.steveice10.opennbt.tag.builtin.IntTag (com.github.steveice10.opennbt.tag.builtin.LongTag and com.github.steveice10.opennbt.tag.builtin.IntTag are in unnamed module of loader com.soulfiremc.util.SFContextClassLoader @2ac1fdc4)
[00:53:37 ERROR] [SoulFireConsole]: at com.soulfiremc.server.protocol.bot.SessionDataManager.onRegistry(SessionDataManager.java:264)
[00:53:37 ERROR] [SoulFireConsole]: at net.lenni0451.lambdaevents.LambdaManager.call(LambdaManager.java:168)
[00:53:37 ERROR] [SoulFireConsole]: at net.lenni0451.lambdaevents.LambdaManager.call(LambdaManager.java:132)
[00:53:37 ERROR] [SoulFireConsole]: at com.soulfiremc.server.protocol.SFSessionListener.packetReceived(SFSessionListener.java:57)
[00:53:37 ERROR] [SoulFireConsole]: at com.github.steveice10.packetlib.tcp.TcpSession.callPacketReceived(TcpSession.java:161)
[00:53:37 ERROR] [SoulFireConsole]: at com.soulfiremc.server.protocol.netty.ViaClientSession.tick(ViaClientSession.java:346)
[00:53:37 ERROR] [SoulFireConsole]: at com.soulfiremc.server.protocol.BotConnection.tick(BotConnection.java:74)
[00:53:37 ERROR] [SoulFireConsole]: at com.soulfiremc.server.plugins.BotTicker.lambda$startTicker$0(BotTicker.java:47)
[00:53:37 ERROR] [SoulFireConsole]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[00:53:37 ERROR] [SoulFireConsole]: at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[00:53:37 ERROR] [SoulFireConsole]: at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[00:53:37 ERROR] [SoulFireConsole]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[00:53:37 ERROR] [SoulFireConsole]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[00:53:37 ERROR] [SoulFireConsole]: at com.soulfiremc.server.protocol.ExecutorManager.lambda$getThreadFactory$0(ExecutorManager.java:103)
[00:53:37 ERROR] [SoulFireConsole]: at java.base/java.lang.Thread.run(Thread.java:1583)
[00:53:37 WARN] [Bot_1]: Received entity teleport packet for unknown entity 11
[00:53:37 WARN] [Bot_1]: Received entity head rotation packet for unknown entity 11
[00:53:37 INFO] [ChatMessageLogger]: <Server> q2yWHUTWK2 joined the world
```

### How can we reproduce what you got?

- Set up Hyperion (`cargo run --release --bin infection`)
- Set up SoulFire with these settings
![image](https://github.com/AlexProgrammerDE/SoulFire/assets/29845135/fe8e343a-4616-432e-bda2-cf33e282e276)
- Run

### SoulFire/Error Logs

https://gist.github.com/TheDevMinerTV/9fd8cca885c0a8a33ffb0f7d5b169fe9

### SoulFire Version

1.7.0

### Java Version

```
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Corretto-21.0.3.9.1 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.3.9.1 (build 21.0.3+9-LTS, mixed mode, sharing)
```

**Comment by AlexProgrammerDE** [comment]
Seems like hyperion sends a different registry than normal. I'll have to support more flexible nbt registry mapping.

**Comment by AlexProgrammerDE** [comment]
![2024-05-06_19 43 42](https://github.com/AlexProgrammerDE/SoulFire/assets/40795980/1b8592d0-3e2c-4c89-a8e5-7faba16b9f33)
Will be fixed by the release of 1.8.0. The new NBT lib fixed the issue.

**Comment by TheDevMinerTV** [comment]
Alright, nice. Thank you!

**Comment by AlexProgrammerDE** [comment]
1.8.0 released with this fixed.
