### ISSUE TITLE
Cant Batch add Alot of accounts 

### ISSUE THREAD

**Issue by Satanaelcode** [AlexProgrammerDE/SoulFire#585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your issue

This is a Follow up on #583 
issue is that if i add alot of accounts even tho some of them are valid and it logges in
at the end it says it failed to import accounts

i cant really tell if this is the stacktrace because this one is at the end and longer then the regular account could not auth stacktrace

Stacktrace:
```
[15:09:51 ERROR] [MCAuthServiceImpl]: Error authenticating account java.lang.IllegalArgumentException: Invalid data!
	at com.soulfiremc.server.account.MSJavaCredentialsAuthService.createData(MSJavaCredentialsAuthService.java:55) ~[?:?]
	at com.soulfiremc.server.account.MSJavaCredentialsAuthService.createData(MSJavaCredentialsAuthService.java:30) ~[?:?]
	at com.soulfiremc.server.account.MCAuthService.createDataAndLogin(MCAuthService.java:80) ~[?:?]
	at com.soulfiremc.server.grpc.MCAuthServiceImpl.lambda$loginCredentials$1(MCAuthServiceImpl.java:45) ~[?:?]
	at com.soulfiremc.server.util.SFHelpers.maxFutures(SFHelpers.java:93) ~[?:?]
	at com.soulfiremc.server.grpc.MCAuthServiceImpl.loginCredentials(MCAuthServiceImpl.java:44) ~[?:?]
	at com.soulfiremc.grpc.generated.MCAuthServiceGrpc$MethodHandlers.invoke(MCAuthServiceGrpc.java:327) ~[?:?]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) ~[?:?]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) ~[?:?]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) ~[?:?]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) ~[?:?]
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) ~[?:?]
	at com.linecorp.armeria.internal.server.grpc.AbstractServerCall.invokeOnMessage(AbstractServerCall.java:399) ~[?:?]
	at com.linecorp.armeria.internal.server.grpc.AbstractServerCall.onRequestMessage(AbstractServerCall.java:365) ~[?:?]
	at com.linecorp.armeria.server.grpc.UnaryServerCall.lambda$startDeframing$0(UnaryServerCall.java:109) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2372) ~[?:?]
	at com.linecorp.armeria.server.grpc.UnaryServerCall.startDeframing(UnaryServerCall.java:102) ~[?:?]
	at com.linecorp.armeria.server.grpc.FramedGrpcService.startCall(FramedGrpcService.java:334) ~[?:?]
	at com.linecorp.armeria.server.grpc.FramedGrpcService.startCall(FramedGrpcService.java:308) ~[?:?]
	at com.linecorp.armeria.server.grpc.FramedGrpcService.doPost(FramedGrpcService.java:274) ~[?:?]
	at com.linecorp.armeria.server.AbstractHttpService.serve(AbstractHttpService.java:57) ~[?:?]
	at com.linecorp.armeria.server.AbstractHttpService.serve(AbstractHttpService.java:42) ~[?:?]
	at com.linecorp.armeria.server.grpc.UnframedGrpcService.serve(UnframedGrpcService.java:109) ~[?:?]
	at com.linecorp.armeria.server.grpc.UnframedGrpcService.serve(UnframedGrpcService.java:64) ~[?:?]
	at com.linecorp.armeria.server.cors.CorsService.serve(CorsService.java:143) ~[?:?]
	at com.linecorp.armeria.server.cors.CorsService.serve(CorsService.java:52) ~[?:?]
	at com.linecorp.armeria.server.metric.MetricCollectingService.serve(MetricCollectingService.java:109) ~[?:?]
	at com.linecorp.armeria.internal.server.RouteDecoratingService.serve(RouteDecoratingService.java:132) ~[?:?]
	at com.linecorp.armeria.internal.server.RouteDecoratingService.serve(RouteDecoratingService.java:79) ~[?:?]
	at com.linecorp.armeria.server.logging.LoggingService.serve(LoggingService.java:86) ~[?:?]
	at com.linecorp.armeria.internal.server.RouteDecoratingService$InitialDispatcherService.serve(RouteDecoratingService.java:202) ~[?:?]
	at com.linecorp.armeria.server.HttpServerHandler.serve0(HttpServerHandler.java:490) ~[?:?]
	at com.linecorp.armeria.server.HttpServerHandler.lambda$handleRequest$3(HttpServerHandler.java:396) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179) ~[?:?]
	at com.linecorp.armeria.server.AggregatingDecodedHttpRequest.close(AggregatingDecodedHttpRequest.java:201) ~[?:?]
	at com.linecorp.armeria.server.Http1RequestDecoder.channelRead(Http1RequestDecoder.java:356) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
	at com.linecorp.armeria.server.HttpServerUpgradeHandler.channelRead(HttpServerUpgradeHandler.java:227) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[?:?]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) ~[?:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[?:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) ~[?:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[?:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
[15:09:51 WARN] [RPCServer]: [sreqId=9a9b94cd, chanId=61525c72, raddr=127.0.0.1:34900, laddr=127.0.0.1:38765][h1c://debian2/soulfire.v1.MCAuthService/loginCredentials#POST] Request: {startTime=2024-11-19T14:06:50.855Z(1732025210855877), length=18880B, duration=180s(180691668021ns), cause=io.grpc.StatusRuntimeException: INTERNAL: Invalid data!, scheme=gproto-web-text+h1c, name=loginCredentials, headers=[:method=POST, :scheme=http, :path=/soulfire.v1.MCAuthService/loginCredentials, host=127.0.0.1:38765, user-agent=Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0, accept=application/grpc-web-text, accept-language=en-US,en;q=0.5, accept-encoding=gzip, deflate, br, zstd, referer=http://localhost:3000/, authorization=****, content-type=application/grpc-web-text, x-grpc-web=1, content-length=18880, origin=http://localhost:3000, sec-fetch-dest=empty, sec-fetch-mode=cors, sec-fetch-site=cross-site, priority=u=4], content=****}[15:09:51 WARN] [RPCServer]: [sreqId=9a9b94cd, chanId=61525c72, raddr=127.0.0.1:34900, laddr=127.0.0.1:38765][h1c://debian2/soulfire.v1.MCAuthService/loginCredentials#POST] Response: {startTime=2024-11-19T14:09:51.548Z(1732025391548426), length=0B, duration=1036µs(1036482ns), totalDuration=180s(180693590011ns), cause=io.grpc.StatusRuntimeException: INTERNAL: Invalid data!, headers=[EOS], :status=200, content-type=application/grpc-web-text+proto, grpc-encoding=identity, grpc-accept-encoding=gzip, grpc-status=13, grpc-message=Invalid data!, content-length=0, access-control-allow-origin=*, access-control-allow-headers=content-type,x-user-agent,x-grpc-web,authorization, access-control-expose-headers=grpc-status,grpc-message,armeria.grpc.throwableproto-bin, server=Armeria/1.31.0, date=Tue, 19 Nov 2024 14:09:51 GMT], content=****} io.grpc.StatusRuntimeException: INTERNAL: Invalid data!
	at io.grpc.Status.asRuntimeException(Status.java:532) ~[?:?]
	at com.linecorp.armeria.internal.common.grpc.StatusAndMetadata.asRuntimeException(StatusAndMetadata.java:53) ~[?:?]
	at com.linecorp.armeria.internal.common.grpc.GrpcLogUtil.rpcResponse(GrpcLogUtil.java:62) ~[?:?]
	at com.linecorp.armeria.server.grpc.UnaryServerCall.doClose(UnaryServerCall.java:177) ~[?:?]
	at com.linecorp.armeria.internal.server.grpc.AbstractServerCall.doClose(AbstractServerCall.java:277) ~[?:?]
	at com.linecorp.armeria.internal.server.grpc.AbstractServerCall.close(AbstractServerCall.java:240) ~[?:?]
	at com.linecorp.armeria.internal.server.grpc.AbstractServerCall.close(AbstractServerCall.java:230) ~[?:?]
	at com.linecorp.armeria.internal.server.grpc.AbstractServerCall.close(AbstractServerCall.java:225) ~[?:?]
	at com.linecorp.armeria.internal.server.grpc.AbstractServerCall.invokeOnMessage(AbstractServerCall.java:402) ~[?:?]
	at com.linecorp.armeria.internal.server.grpc.AbstractServerCall.onRequestMessage(AbstractServerCall.java:365) ~[?:?]
	at com.linecorp.armeria.server.grpc.UnaryServerCall.lambda$startDeframing$0(UnaryServerCall.java:109) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2372) ~[?:?]
	at com.linecorp.armeria.server.grpc.UnaryServerCall.startDeframing(UnaryServerCall.java:102) ~[?:?]
	at com.linecorp.armeria.server.grpc.FramedGrpcService.startCall(FramedGrpcService.java:334) ~[?:?]
	at com.linecorp.armeria.server.grpc.FramedGrpcService.startCall(FramedGrpcService.java:308) ~[?:?]
	at com.linecorp.armeria.server.grpc.FramedGrpcService.doPost(FramedGrpcService.java:274) ~[?:?]
	at com.linecorp.armeria.server.AbstractHttpService.serve(AbstractHttpService.java:57) ~[?:?]
	at com.linecorp.armeria.server.AbstractHttpService.serve(AbstractHttpService.java:42) ~[?:?]
	at com.linecorp.armeria.server.grpc.UnframedGrpcService.serve(UnframedGrpcService.java:109) ~[?:?]
	at com.linecorp.armeria.server.grpc.UnframedGrpcService.serve(UnframedGrpcService.java:64) ~[?:?]
	at com.linecorp.armeria.server.cors.CorsService.serve(CorsService.java:143) ~[?:?]
	at com.linecorp.armeria.server.cors.CorsService.serve(CorsService.java:52) ~[?:?]
	at com.linecorp.armeria.server.metric.MetricCollectingService.serve(MetricCollectingService.java:109) ~[?:?]
	at com.linecorp.armeria.internal.server.RouteDecoratingService.serve(RouteDecoratingService.java:132) ~[?:?]
	at com.linecorp.armeria.internal.server.RouteDecoratingService.serve(RouteDecoratingService.java:79) ~[?:?]
	at com.linecorp.armeria.server.logging.LoggingService.serve(LoggingService.java:86) ~[?:?]
	at com.linecorp.armeria.internal.server.RouteDecoratingService$InitialDispatcherService.serve(RouteDecoratingService.java:202) ~[?:?]
	at com.linecorp.armeria.server.HttpServerHandler.serve0(HttpServerHandler.java:490) ~[?:?]
	at com.linecorp.armeria.server.HttpServerHandler.lambda$handleRequest$3(HttpServerHandler.java:396) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179) ~[?:?]
	at com.linecorp.armeria.server.AggregatingDecodedHttpRequest.close(AggregatingDecodedHttpRequest.java:201) ~[?:?]
	at com.linecorp.armeria.server.Http1RequestDecoder.channelRead(Http1RequestDecoder.java:356) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
	at com.linecorp.armeria.server.HttpServerUpgradeHandler.channelRead(HttpServerUpgradeHandler.java:227) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[?:?]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) ~[?:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[?:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) ~[?:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[?:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.IllegalArgumentException: Invalid data!
	at com.soulfiremc.server.account.MSJavaCredentialsAuthService.createData(MSJavaCredentialsAuthService.java:55) ~[?:?]
	at com.soulfiremc.server.account.MSJavaCredentialsAuthService.createData(MSJavaCredentialsAuthService.java:30) ~[?:?]
	at com.soulfiremc.server.account.MCAuthService.createDataAndLogin(MCAuthService.java:80) ~[?:?]
	at com.soulfiremc.server.grpc.MCAuthServiceImpl.lambda$loginCredentials$1(MCAuthServiceImpl.java:45) ~[?:?]
	at com.soulfiremc.server.util.SFHelpers.maxFutures(SFHelpers.java:93) ~[?:?]
	at com.soulfiremc.server.grpc.MCAuthServiceImpl.loginCredentials(MCAuthServiceImpl.java:44) ~[?:?]
	at com.soulfiremc.grpc.generated.MCAuthServiceGrpc$MethodHandlers.invoke(MCAuthServiceGrpc.java:327) ~[?:?]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) ~[?:?]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) ~[?:?]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) ~[?:?]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) ~[?:?]
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) ~[?:?]
	at com.linecorp.armeria.internal.server.grpc.AbstractServerCall.invokeOnMessage(AbstractServerCall.java:399) ~[?:?]
	... 60 more
```

and its not like there are all me getting blocked because example this one got added

```
[15:07:09 INFO] [MinecraftAuth]: Trying to get MSA Code using email and password...
[15:07:10 INFO] [MinecraftAuth]: Got MSA Code
[15:07:10 INFO] [MinecraftAuth]: Getting MSA Token...
[15:07:10 INFO] [MinecraftAuth]: Got MSA Token, expires: 2024-11-20T15:07:10.615+01:00[Europe/Berlin]
[15:07:10 INFO] [MinecraftAuth]: Authenticating device with Xbox Live...
[15:07:13 INFO] [MinecraftAuth]: Got XBL Device Token, expires: 2024-12-03T15:07:13.429+01:00[Europe/Berlin]
[15:07:13 INFO] [MinecraftAuth]: Authenticating with Xbox Live using SISU...
[15:07:14 INFO] [MinecraftAuth]: Got XBL User+Title+XSTS Token, expires: 2024-11-20T07:07:13.987+01:00[Europe/Berlin]
[15:07:14 INFO] [MinecraftAuth]: Authenticating with Minecraft Services...
[15:07:14 INFO] [MinecraftAuth]: Got MC Token, expires: 2024-11-20T15:07:14.957+01:00[Europe/Berlin]
[15:07:14 INFO] [MinecraftAuth]: Getting profile...
[15:07:15 INFO] [MinecraftAuth]: Got MC Profile, name: Rishabhgod3233, uuid: f6579fd8-dfe1-4538-84e4-a8a1f80fc8b0
[15:07:15 INFO] [MinecraftAuth]: Getting player certificates...
[15:07:15 INFO] [MinecraftAuth]: Got player certificates, expires: 2024-11-20T19:53:21.269+01:00[Europe/Berlin]
```

### How can we reproduce what you got?

1. Take a big amount of accounts (if needed i can provide)
2. Try Cred Java Login 
3. add them using any method provided
4. let them all auth.
5. Doesnt Add the accounts and says failed to add accounts.

### SoulFire/Error Logs

https://pastebin.com/9PAXfNNA

### SoulFire Version

SoulFireDedicated-1.15.0-SNAPSHOT

### Java Version

openjdk 22.0.2

**Comment by Satanaelcode** [comment]
Solved in latest Update
